#!/usr/bin/env bash
# kernel_tune.sh — one command that MEASURES the kernel-dispatch thresholds on this box
#                  and writes them back as environment overrides.
#
# WHY THIS EXISTS. The batched-kernel gate in qwen_tts_kernels.c (`g_mm_gate[]`,
# consulted by `qwen_mm_use()`) is a table of DECLARED GUESSES: AMX min_B = 4,
# min_rows = 32, min_cols 32/64, and 2 for VNNI / AVX2 / SMMLA / BFMMLA. On a GCP c3
# (Sapphire Rapids) three generations of SIMD — AMX, AVX-512/VNNI/BF16, AVX2 — compete
# for the same projection, and choosing between them with hand-written constants wastes
# the machine. This script sweeps B x the model's real shapes x every kernel the ISA
# offers, at ONE thread and at full threads, and prints the constants back.
#
# THE ONE THING TO READ IN THE OUTPUT: a kernel flagged "WINS ONLY WITH THE THREAD
# POOL" is not winning. It is amortizing thread-pool launches over one call instead of
# B — measured on M1 on 2026-08-18, the bf16 twin's famous "1.70x" was exactly that
# (0.79x at one real thread, once --matmat-bench stopped ignoring -j).
#
# Usage:
#   tests/kernel_tune.sh [MODEL_DIR] [-j N] [--quick] [-o OUTDIR]
#     MODEL_DIR   take the projection shapes from MODEL_DIR/config.json (no weights are
#                 loaded). Without it: the declared 0.6B + 1.7B + code-predictor shapes.
#     -j N        full-thread count (default: all cores). The j=1 row is always measured.
#     --quick     skip the shapes above 4M elements (~2x faster, hides the FFN case)
#     -o OUTDIR   default outputs/kernel-tune/<host>_<date>
#
# Writes into OUTDIR:
#     tune.txt    the full table + the summary (what you read)
#     tune.json   the whole grid, so two boxes can be diffed
#     tune.env    the export lines — `source` it, or paste it into the systemd unit
#
# Then: `set -a; . OUTDIR/tune.env; set +a` and re-run whatever you were measuring.
# If nothing changes, the thresholds were not the binding constraint — say so, rather
# than keeping the exports because they look tuned.
set -u
cd "$(dirname "$0")/.." || exit 1
ROOT=$PWD
BIN=$ROOT/qwen_tts
[ -x "$BIN" ] || { echo "build first: make blas"; exit 1; }

MODEL=""; JOBS=""; QUICK=0; OUT=""
while [ $# -gt 0 ]; do
    case "$1" in
        -j)      JOBS="${2:-}"; shift 2 ;;
        -j*)     JOBS="${1#-j}"; shift ;;
        --quick) QUICK=1; shift ;;
        -o)      OUT="${2:-}"; shift 2 ;;
        -h|--help) sed -n '2,30p' "$0"; exit 0 ;;
        -*)      echo "unknown option: $1"; exit 2 ;;
        *)       MODEL="$1"; shift ;;
    esac
done

if [ -z "$JOBS" ]; then
    JOBS=$(sysctl -n hw.ncpu 2>/dev/null || nproc 2>/dev/null || echo 4)
fi
HOST=$(hostname -s 2>/dev/null || echo box)
[ -n "$OUT" ] || OUT="$ROOT/outputs/kernel-tune/${HOST}_$(date +%Y-%m-%d_%H%M%S)"
case "$OUT" in /*) ;; *) OUT="$ROOT/$OUT" ;; esac      # absolute: this file is pasted around
mkdir -p "$OUT" || exit 1

TXT=$OUT/tune.txt; JSON=$OUT/tune.json; ENVF=$OUT/tune.env

# The box first, then the numbers: SMT on, a wrong governor or two NUMA nodes change how
# every line below reads, and reading them afterwards is reading them too late.
{
    echo "# kernel_tune — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# host    : $HOST  $(uname -smr)"
    echo "# threads : full=$JOBS  (the j=1 row is measured too, always)"
    echo "# model   : ${MODEL:-<declared 0.6B+1.7B defaults>}"
    echo
    "$BIN" --caps 2>&1
    echo
} > "$TXT"

echo "measuring (this takes a few minutes; keep the box quiet)..." >&2
ENVV="QWEN_TUNE_JSON=$JSON"
[ "$QUICK" = "1" ] && ENVV="$ENVV QWEN_TUNE_QUICK=1"
if [ -n "$MODEL" ]; then
    env $ENVV "$BIN" --matmat-tune -j "$JOBS" -d "$MODEL" >> "$TXT" 2>&1
else
    env $ENVV "$BIN" --matmat-tune -j "$JOBS" >> "$TXT" 2>&1
fi
RC=$?

# The .env is generated from the report, not written twice: one source of truth, and a
# threshold that changes in the C table cannot silently disagree with the script.
{
    echo "# generated by tests/kernel_tune.sh on $HOST, $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# measured, not guessed — see $TXT for the grid these came from."
    echo "# usage:  set -a; . $ENVF; set +a"
    # everything the report put under "CONFIGURATION FOR THIS BOX", verbatim: the
    # `export` lines AND the `#` advisories (an opt-in kernel confirmed OFF, a kernel
    # that loses but has no kill switch). Dropping the comments would turn "measured
    # and correct as-is" into "the tuner found nothing", which reads as a failed run.
    awk '/CONFIGURATION FOR THIS BOX/ {inblk=1; next}
         inblk && /^══/            {inblk=0}
         inblk && /[^ ]/           {sub(/^[[:space:]]+/, ""); print}' "$TXT"
} > "$ENVF"

cat "$TXT"
echo
echo "── written ───────────────────────────────────────────────────────────"
echo "  table : $TXT"
echo "  grid  : $JSON"
echo "  env   : $ENVF"
echo
echo "apply without rebuilding:"
echo "  set -a; . $ENVF; set +a"
exit $RC

# ── Makefile snippet (NOT applied here — wire it in yourself) ──────────────────
#
# kernel-tune: $(TARGET)
# 	@tests/kernel_tune.sh $(MODEL_DIR)
#
# kernel-tune-quick: $(TARGET)
# 	@tests/kernel_tune.sh --quick $(MODEL_DIR)
#
# (tabs, not spaces, in the recipe lines.)
