#!/usr/bin/env bash
set -u
cd "$(dirname "$0")/.." || exit 1
ROOT=$PWD
BIN=$ROOT/qwen_tts
[ -x "$BIN" ] || { echo "build first: make blas"; exit 1; }

MODEL=""; JOBS=""; QUICK=0; OUT=""
while [ $# -gt 0 ]; do
    case "$1" in
        -j)      JOBS="${2:-}"; shift 2 ;;
        -j*)     JOBS="${1#-j}"; shift ;;
        --quick) QUICK=1; shift ;;
        -o)      OUT="${2:-}"; shift 2 ;;
        -h|--help) sed -n '2,30p' "$0"; exit 0 ;;
        -*)      echo "unknown option: $1"; exit 2 ;;
        *)       MODEL="$1"; shift ;;
    esac
done

if [ -z "$JOBS" ]; then
    JOBS=$(sysctl -n hw.ncpu 2>/dev/null || nproc 2>/dev/null || echo 4)
fi
HOST=$(hostname -s 2>/dev/null || echo box)
[ -n "$OUT" ] || OUT="$ROOT/outputs/kernel-tune/${HOST}_$(date +%Y-%m-%d_%H%M%S)"
case "$OUT" in /*) ;; *) OUT="$ROOT/$OUT" ;; esac      # absolute: this file is pasted around
mkdir -p "$OUT" || exit 1

TXT=$OUT/tune.txt; JSON=$OUT/tune.json; ENVF=$OUT/tune.env

{
    echo "# kernel_tune — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# host    : $HOST  $(uname -smr)"
    echo "# threads : full=$JOBS  (the j=1 row is measured too, always)"
    echo "# model   : ${MODEL:-<declared 0.6B+1.7B defaults>}"
    echo
    "$BIN" --caps 2>&1
    echo
} > "$TXT"

echo "measuring (this takes a few minutes; keep the box quiet)..." >&2
ENVV="QWEN_TUNE_JSON=$JSON"
[ "$QUICK" = "1" ] && ENVV="$ENVV QWEN_TUNE_QUICK=1"
if [ -n "$MODEL" ]; then
    env $ENVV "$BIN" --matmat-tune -j "$JOBS" -d "$MODEL" >> "$TXT" 2>&1
else
    env $ENVV "$BIN" --matmat-tune -j "$JOBS" >> "$TXT" 2>&1
fi
RC=$?

{
    echo "# generated by tests/kernel_tune.sh on $HOST, $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# measured, not guessed — see $TXT for the grid these came from."
    echo "# usage:  set -a; . $ENVF; set +a"
    awk '/CONFIGURATION FOR THIS BOX/ {inblk=1; next}
         inblk && /^══/            {inblk=0}
         inblk && /[^ ]/           {sub(/^[[:space:]]+/, ""); print}' "$TXT"
} > "$ENVF"

cat "$TXT"
echo
echo "── written ───────────────────────────────────────────────────────────"
echo "  table : $TXT"
echo "  grid  : $JSON"
echo "  env   : $ENVF"
echo
echo "apply without rebuilding:"
echo "  set -a; . $ENVF; set +a"
exit $RC
